config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#new'

  resources :projects, except: :show do
    resources :tasks, only: %i[index new]
    resources :gantt_chart, only: :index
  end

  scope '/api/:project_id' do
    get '/data', to: 'gantt_chart#data'

    post '/task', to: 'tasks#add'
    put '/task/:id', to: 'tasks#update'
    delete '/task/:id', to: 'tasks#delete'

    post '/link', to: 'link#add'
    put '/link/:id', to: 'link#update'
    delete '/link/:id', to: 'link#delete'
  end

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: links
#
#  id         :bigint           not null, primary key
#  link_type  :string(1)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :bigint           not null
#  source_id  :bigint           not null
#  target_id  :bigint           not null
#
# Indexes
#
#  index_links_on_project_id  (project_id)
#  index_links_on_source_id   (source_id)
#  index_links_on_target_id   (target_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#  fk_rails_...  (source_id => tasks.id)
#  fk_rails_...  (target_id => tasks.id)
#
class Link < ApplicationRecord
  belongs_to :project

  belongs_to :source_task, class_name: 'Task', foreign_key: 'source_id'
  belongs_to :target_task, class_name: 'Task', foreign_key: 'target_id'
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  end_date   :datetime
#  name       :string
#  start_date :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  has_one_attached :file

  has_many :tasks, dependent: :destroy
  has_many :links, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tasks
#
#  id                   :bigint           not null, primary key
#  completed            :boolean          default(FALSE)
#  description          :text
#  duration             :integer          not null
#  end_date             :datetime         not null
#  name                 :string           not null
#  percentage_completed :integer          default(0), not null
#  start_date           :datetime         not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  parent_id            :bigint
#  project_id           :bigint           not null
#
# Indexes
#
#  index_tasks_on_parent_id   (parent_id)
#  index_tasks_on_project_id  (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => tasks.id)
#  fk_rails_...  (project_id => projects.id)
#
class Task < ApplicationRecord
  belongs_to :project

  belongs_to :parent, class_name: 'Task', optional: true
  has_many :subtasks, class_name: 'Task', foreign_key: 'parent_id', dependent: :destroy

  has_many :source_links, class_name: 'Link', foreign_key: :source_id, dependent: :destroy
  has_many :target_links, class_name: 'Link', foreign_key: :target_id, dependent: :destroy

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def not_found
    render status: :not_found
  end

  def internal_server_error
    render status: :internal_server_error
  end
end

app/controllers/gantt_chart_controller.rb
# frozen_string_literal: true

class GanttChartController < ApplicationController
  layout 'gantt'

  def index
    @project = Project.find(params[:project_id])
  end

  def data
    project = Project.find(params[:project_id])
    tasks = project.tasks
    links = project.links

    render json: {
      data: tasks.map do |task|
        {
          id: task.id,
          text: task.name,
          start_date: task.start_date.to_formatted_s(:db),
          duration: task.duration,
          progress: task.percentage_completed.to_f / 100,
          parent: task.parent_id,
          open: true
        }
      end,
      links: links.map do |link|
        {
          id: link.id,
          source: link.source_id,
          target: link.target_id,
          type: link.link_type
        }
      end
    }
  end
end

app/controllers/link_controller.rb
# frozen_string_literal: true

class LinkController < ApplicationController
  before_action :link, only: %i[update delete]
  protect_from_forgery

  def update
    link.source_id = params['source']
    link.target_id = params['target']
    link.link_type = params['type']
    link.project_id = params[:project_id]
    link.save

    render json: { action: 'updated' }
  end

  def add
    link = Link.create(
      source_id: params['source'],
      target_id: params['target'],
      link_type: params['type'],
      project_id: params[:project_id]
    )

    render json: { action: 'inserted', tid: link.id }
  end

  def delete
    link.destroy
    render json: { action: 'deleted' }
  end

  private

  def link
    @link ||= Link.find(params['id'])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      MppFileHandlerService.new(@project).read_project

      redirect_to projects_path, notice: 'Project created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @tasks = @project.tasks
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_path, notice: 'Project destroyed'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :file)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  protect_from_forgery

  def update
    task = Task.find(params['id'])
    task.name = params['text']
    task.start_date = params['start_date']
    task.end_date = params['end_date']
    task.duration = params['duration']
    task.percentage_completed = params['progress'] || 0
    task.save

    render json: { action: 'updated' }
  end

  def add
    parent_id = params['parent'].to_i.positive? ? params['parent'] : nil
    task_created = Task.create(
      name: params['text'],
      start_date: params['start_date'],
      end_date: params['end_date'],
      duration: params['duration'],
      percentage_completed: params['progress'],
      parent_id: parent_id,
      project_id: params['project_id']
    )

    render json: { action: 'inserted', tid: task_created.id }
  end

  def delete
    Task.find(params[:id]).destroy
    render json: { action: 'deleted' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/gantt_chart/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.css' %>
  <%= javascript_include_tag 'https://cdn.dhtmlx.com/gantt/edge/dhtmlxgantt.js' %>
<% end %>

<div class="flex justify-start space-x-4 md:space-x-32 items-center ml-5 my-2">
  <%= link_to projects_path, class: 'hover:underline inline-flex items-center text-sm md:text-md leading-4 font-bold rounded-lg text-blue-600 hover:text-blue-400' do %>
    <span class="mr-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
      </svg>
    </span>
    Back to project
  <% end %>
  <h1 class="font-bold text-3xl m" >Gantt Chart - <%= @project.name %></h1>
</div>

<div id="gantt_here" style='width:100%; height:800px;' data-controller="chart--gantt" data-chart--gantt-project-value="<%= params[:project_id]%>"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GanttChart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.1/dist/frappe-gantt.min.css">
    <script async src="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.1/dist/frappe-gantt.min.js"></script>
  </head>

  <body class="bg-gray-100">
    <main class="container mx-auto mt-28 px-5">
      <%= render partial: 'shared/notification' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/gantt.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GanttChart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.1/dist/frappe-gantt.min.css">
    <script async src="https://cdn.jsdelivr.net/npm/frappe-gantt@0.6.1/dist/frappe-gantt.min.js"></script>

    <%= yield(:head) %>
  </head>

  <body class="bg-gray-100">
    <main class="">
      <%= render partial: 'shared/notification' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_file.html.erb
<%= form_with model: project do |form| %>
  <div class="mb-6">
    <%= form.label :name, class: 'inline-block font-bold text-xl mb-2 text-gray-700' %>
    <%= form.text_field :name, class: 'border border-gray-200 rounded p-2 w-full', required: true, placeholder: 'Project name' %>
  </div>

  <div class="mb-6">
    <%= form.label :file, 'Choose a file to upload', class: 'inline-block text-lg mb-2 text-gray-700 font-bold text-xl' %>
    <%= form.file_field :file, class: 'bg-white border rounded-lg py-4 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-full', required: true, accept: '.mpp' %>
  </div>

  <div class="flex justify-end">
    <%= link_to 'Back to projects', projects_path, class: 'text-blue-400 underline ml-4 hover:text-blue-700 py-2 px-4 rounded' unless current_page?('/') %>
    <%= form.submit class: 'mr-3 rounded-md cursor-pointer bg-blue-100 px-5 py-2 px-10 hover:bg-blue-300 font-bold' %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div class="mb-6">
    <%= form.label :name, class: 'inline-block font-bold text-lg mb-2 text-gray-700' %>
    <%= form.text_field :name, class: 'border border-gray-200 rounded p-2 w-full', required: true, placeholder: 'Project name' %>
  </div>

  <div class="mb-6">
    <%= form.label :start_date, class: 'inline-block text-lg font-bold mb-2 text-gray-700' %>
    <%= form.date_field :start_date, class: 'border border-gray-200 rounded p-2 w-full' %>
  </div>

  <div class="mb-6">
    <%= form.label :end_date, class: 'inline-block text-lg font-bold mb-2 text-gray-700' %>
    <%= form.date_field :end_date, class: 'border border-gray-200 rounded p-2 w-full' %>
  </div>

  <div class="flex justify-end">
    <%= link_to 'Back to projects', projects_path, class: 'text-blue-400 underline ml-4 hover:text-blue-700 py-2 px-4 rounded' %>
    <%= form.submit class: 'mr-3 rounded-md cursor-pointer bg-blue-100 px-5 py-2 px-10 hover:bg-blue-300 font-bold' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr class="hover:bg-gray-50">
  <td class="px-6 py-4 whitespace-nowrap">
    <div class="flex items-center">
      <div class="ml-4">
        <div class="text-sm font-medium text-blue-900">
          <%= project.name %>
        </div>
      </div>
    </div>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
    <%= project.start_date.strftime("%A, %B %d, %Y") %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
    <%= project.end_date.strftime("%A, %B %d, %Y") %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
    <div class="flex justify-between items-center">
      <%= link_to project_gantt_chart_index_path(project.id), class: 'inline-flex items-center pl-1.5 pr-3 md:pl-2 md:pr-4 py-1.5 border border-transparent text-sm md:text-md leading-4 font-bold rounded-lg text-gray-900 bg-cyan-300 hover:bg-cyan-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-turquoise-500' do %>
        <span>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 3m8.5-3l1 3m0 0l.5 1.5m-.5-1.5h-9.5m0 0l-.5 1.5m.75-9l3-3 2.148 2.148A12.061 12.061 0 0116.5 7.605" />
          </svg>
        </span>
        Gantt chart
      <% end %>
      <%= link_to 'Edit', edit_project_path(project), class: 'text-indigo-600 hover:text-indigo-900' %>
      <%= link_to 'Delete', project_path(project), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this project?' }, class: 'text-red-600 hover:text-red-900' %>
    </div>
  </td>
</tr>

app/views/projects/edit.html.erb
<div>
  <div class="bg-gray-50 border-2 border-gray-200 rounded p-6 max-w-lg mx-auto mt-10 shadow">
    <h1 class="font-bold text-2xl mb-5">Edit project</h1>
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<% if @projects&.count.positive? %>
  <div class="flex">
    <%= link_to new_project_path, class: 'inline-flex items-center pl-1.5 pr-3 md:pl-2 md:pr-4 py-1.5 border border-transparent text-sm md:text-md leading-4 font-bold rounded-lg text-gray-900 bg-green-300 hover:bg-green-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-turquoise-500' do %>
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
      </span>
      Create new project
    <% end %>
  </div>

  <div class="mt-5">  
    <div class="border-b border-gray-300 pt-5">
      <h1 class="text-2xl md:text-3xl font-bold text-gray-800 pb-3">
        Projects
      </h1>
    </div>
    <div class="flex flex-col mt-3">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Start date
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    End date
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <%= render partial: 'project', collection: @projects %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <main class="grid min-h-full place-items-center px-6 py-24 sm:py-32 lg:px-8">
    <div class="text-center">
      <h1 class="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-5xl">No projects to display</h1>
      <div class="mt-10 flex items-center justify-center gap-x-6">
        <%= link_to new_project_path, class: 'inline-flex items-center pl-1.5 pr-3 md:pl-2 md:pr-4 py-1.5 border border-transparent text-sm md:text-md leading-4 font-bold rounded-lg text-gray-900 bg-green-300 hover:bg-green-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-turquoise-500' do %>
          <span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
          </span>
          Create new project
        <% end %>
      </div>
    </div>
  </main>
<% end %>

app/views/projects/new.html.erb
<div>
  <div>
    <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6x text-center">
      Import and visualize your <span class="text-blue-600">Microsoft Project</span> in a <span class="text-teal-500">Gantt Chart</span>
    </h1>

    <div class="bg-gray-50 border-2 border-gray-200 rounded p-6 max-w-lg mx-auto mt-10 shadow">
      <%= render 'file', project: @project %>
    </div>
  </div>
</div>

app/views/shared/_notification.html.erb
<div>  
  <% if notice.present? %>
    <div class="rounded-md bg-green-50 p-4 border-solid border-2 border-green-400" data-controller="display" data-display-target="element">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <p class="text-sm font-medium text-green-800">
            <%= notice %>
          </p>
        </div>
        <div class="ml-auto pl-3">
          <div class="-mx-1.5 -my-1.5">
            <button data-action="click->display#hide" type="button" class="inline-flex bg-green-50 rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-50 focus:ring-green-600">
              <span class="sr-only">Dismiss</span>
              <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="rounded-md bg-red-50 p-4 border-solid border-2 border-red-400" data-controller="display" data-display-target="element">
      <div class="flex">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <p class="text-sm font-medium text-red-800">
            <%= alert %>
          </p>
        </div>
        <div class="ml-auto pl-3">
          <div class="-mx-1.5 -my-1.5">
            <button data-action="click->display#hide" type="button" class="inline-flex bg-red-50 rounded-md p-1.5 text-red-500 hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-red-50 focus:ring-red-600">
              <span class="sr-only">Dismiss</span>
              <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: task, url: project_tasks_path  do |form| %>
  <div class="mb-6">
    <%= form.label :name, class: 'text-bold inline-block text-lg mb-2 font-bold ' %>
    <%= form.text_field :name, class: 'border border-gray-200 rounded p-2 w-full', placeholder: 'Task name', required: true %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: 'text-bold inline-block text-lg mb-2 font-bold ' %>
    <%= form.text_area :description, class: 'border border-gray-200 rounded p-2 w-full', placeholder: 'Description of the task' %>
  </div>

  <div class="mb-6">
    <%= form.label :start_date, class: 'text-bold inline-block text-lg font-bold mb-2' %>
    <%= form.date_field :start_date, class: 'border border-gray-200 rounded p-2 w-full', required: true  %>
  </div>

  <div class="mb-6">
    <%= form.label :end_date, class: 'text-bold inline-block text-lg font-bold mb-2' %>
    <%= form.date_field :end_date, class: 'border border-gray-200 rounded p-2 w-full', required: true  %>
  </div>

  <div class="mb-6">
    <%= form.label :completed, class: 'text-bold inline-block text-lg font-bold mb-2' %>
    <%= form.select :completed, [["Complete", true], ["Incomplete", false]], {}, { :class => 'border border-gray-200 rounded p-2 w-full' } %>
  </div>

  <div class="flex justify-end">
    <%= link_to 'Back to project', project_path(id: params[:project_id]), class: 'text-blue-400 underline ml-4 hover:text-blue-700 py-2 px-4 rounded' %>
    <%= form.submit class: 'mr-3 rounded-md cursor-pointer bg-blue-100 px-5 py-2 px-10 hover:bg-blue-300 font-bold' %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<div class="bg-gray-50 border-2 border-gray-200 rounded p-6 max-w-lg mx-auto mt-5 shadow">
  <header class="text-center">
    <h2 class="text-2xl font-bold uppercase mb-1">Create task</h2>
  </header>
  <%= render 'form', task: @task %>
</div>